# Generated by Django 4.1.2 on 2022-10-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_package_description_package_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
