# Generated by Django 4.1.2 on 2022-10-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='origin',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='wrapper',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
