# Generated by Django 4.1.2 on 2022-10-20 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_package_origin_package_wrapper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Work Date')),
                ('type', models.CharField(choices=[('ERR', 'Error'), ('WRK', 'Working'), ('FIN', 'Completed')], default='WRK', max_length=3)),
                ('comment', models.CharField(max_length=150)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.package')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
